# Workflow is a customization of the Python starter
# workflow published in GitHub docs, 
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
#
# The aim is to perform unit test with macOS and linux
# and distinct Python versions.
#
# By: Robert Vogel

name: unit-tests

run-name: ${{ github.actor }} running unit-tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    strategy:
      matrix: 
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies on ${{ matrix.os }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy scipy matplotlib
          python -m pip install git+https://github.com/robert-vogel/pySUMMA.git
      - name: Run unittest for ${{ matrix.python-version }} on ${{ matrix.os }}
        run: |
          python -m unittest
